version: "3"
services:
    mongo_db:
        image: mongo:4.2.16-rc0-bionic
        container_name: mongo-delivery-db
        expose:
            - "27017"
        ports:
            - "27017:27017"
        # volumes:
        #     - ./data/db:/data/db
        environment:
            - ME_CONFIG_MONGODB_SERVER=delivery
        restart: always
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq-delivery
        ports:
            - "5672:5672"
            - "8080:15672"
        restart: always
    shipment_app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        container_name: delivery_service
        environment:
            - ENV_CONFIG=settings.settings.DevelopmentConfig
            - MONGO_HOST=mongo_db
            - MONGO_DB_NAME=delivery
            - RABBITMQ_HOST=rabbitmq
            - WAIT_HOSTS=mongo_db:27017
        volumes:
            - ./project:/app/project
        entrypoint: sh -c "/wait && python /app/server.py"
        depends_on:
            - mongo_db
            - rabbitmq
        ports:
            - "5000:5000"
        restart: on-failure
        stdin_open: true
        tty: true
